### ISSUE TITLE
Positions of responses are not set on some Streamprocessors

### ISSUE THREAD

**Issue by Zelldon** [camunda-zeebe/tasks#35]
See comment below

**Comment by Zelldon** [comment]
Update:

Makes no sense that this cause problem on the client since even if the position is negative on the broker the client must interpret it as positive large value, on which the highest bit is set.

**Comment by ThorbenLindhauer** [comment]
=> There is no possibility that the broker can send an invalid uint64 value.

**Comment by Zelldon** [comment]
In the current protocol definition your fields are per default set to `presence=required`. This means that they mutually exclusive with the null value. 
See page 13 on http://www.smallake.kr/wp-content/uploads/2014/11/Simple-Binary-Encoding-Release-Candidate-2.pdf

On some Streamprocessors, for example TaskinstanceStreamProcessor#LockTaskProcessor, DeploymentStreamProcessor or WorkflowInstanceStreamProcessor the position of the event is not set. in this case the SBE null value will be used (Long#MIN_VALUE). See for example the https://github.com/camunda-zeebe/zeebe/blob/master/broker-core/src/main/java/io/zeebe/broker/transport/clientapi/SubscribedEventWriter.java which defines the position as `protected long position = positionNullValue();`. This is not spec conform.

**Comment by menski** [comment]
I know this is not really an issue here but in our tests we often do asserts like this:

```
assertThat(resp.position()).isGreaterThanOrEqualTo(0L);
assertThat(updatedEvent.position()).isGreaterThan(response.position());
```

Which is not always true as Java doesn't have uints, i.e. ` Long.MAX_VALUE < Long.MAX_VALUE + 1` is false in Java but true in uint world. But I assume our tests will never reach positions higher Long.MAX_VALUE.

But in practice this could have an impact on us. For example raft assumes that positions are always increasing. And maybe we also do this assumption in other places. Don't we for example also check that the position returned from `tryWrite` is bigger then 0? Or do we somehow prevent the position to ever reach a value between Long.MIN_VALUE <= x < -1?

**Comment by ThorbenLindhauer** [comment]
I can't comment on the current state, but I think it would be a good idea to restrict log event positions to uint63 range (and enforce this in the log streams module) as that saves us the fun of dealing with uint64 in Java like you outline.

**Comment by meyerdan** [comment]
Positions must always be increasing and we will never reach Long.MAX_VALUE. If we do, dispatcher breaks. You can calculate when that happens, I did it already at least twice with @menski  and at least once with @Zelldon

**Comment by meyerdan** [comment]
The calculation is based on Size of Dispatcher, the way positions are being generates (long composed of two ints where the first one signifies partitions and the second offest within the partition). Based on this you can calculate how many bytes you can run thorugh dispatcher until Long.MAX_VALUE is reached.
